name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.1.1
      with:
           ....
           .... 
           mamba-version: "*"
           channels: conda-forge
           channel-priority: true
    - name: execute notebooks
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 *.ipynb
